server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          default:
            client-id: bff-client
            client-secret: secret
            scope: openid,profile
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/default
        provider:
          default:
            issuer-uri: http://localhost:9000
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      cors:
        allowedOrigins: http://localhost:3000
        allowedMethods: GET,POST,PUT,DELETE,OPTIONS
        allowedHeaders: '*'
        allowCredentials: true
      routes:
        - id: auth-routes
          uri: http://localhost:9000
          predicates:
            - Path=/oauth2/**
          filters:
            - RemoveRequestHeader=Cookie
            - SaveSession