server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
        client:
          bff-client:
            registration:
              client-id: bff-client
              client-secret: "{noop}secret"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
              redirect-uris:
                - http://localhost:8080/login/oauth2/code/default
              scopes:
                - openid
                - profile